name: CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ master, dev ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: sokkuri/code-reviewer@v1.0.2

  build:
    runs-on: ubuntu-latest
    needs: [ test ]
    container: node:lts-alpine
    steps:
      - uses: actions/checkout@v2.3.4
      - run: |
          npm install
          npm run build
